server:
  port: 10088
spring:
  application:
    name: sc-adminmanageconference-service
  security:
    user:
      name: root
      password: root


eureka:
  client:
    service-url:
      defaultZone: http://root:root@sc:10086/eureka/
    instance:
      prefer-ip-address: true
management:
  security:
    enabled: false

