services:
  mongo:
    image: mongo

pipeline:
#  test:
#    image: taskalive/toolbox
#    environment:
#      - MONGO_URL=mongodb://mongo
#      - SESSION=http://session
#    commands:
#      - pip3 install m3u8
#      - python3 -m unittest

  build:
    image: registry.cn-hangzhou.aliyuncs.com/docker_io_allen/docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build -t starchair/review-process-service:latest .

  deploy:
    image: registry.cn-hangzhou.aliyuncs.com/docker_io_allen/docker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm -f review-process-service || true
      - docker image tag starchair/review-process-service:latest starchair/review-process-service:master
      - docker rmi $(docker images | grep "none" | awk '{print $3}') || true
      - >
        docker run -d --restart always --network=starchair
        -v /srv/starchair/ReviewProcessService:/everything -p 5006:5006
        --name review-process-service starchair/review-process-service:master
    when:
      branch: master