server:
  port: 10086

spring:
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    hostname: se
    perfer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone:  http://root:root@se:10086/eureka/

