version: '3'
services:
  eureka-service:
    hostname: sc
    image: sc/sc-eureka-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: eureka-service
    ports:
      - 10010:10010


  applymeeting-service:
    hostname: sc
    image: sc/applymeeting-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/           
    container_name: applymeeting-service
    ports:
      - 10011:10011
  
  adminmanageconference-service:
    hostname: sc
    image: sc/adminmanageconference-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: adminmanageconference-service
    ports:
      - 10012:10012


  startsubmit-service:
    hostname: sc
    image: sc/sc-startsubmit-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: startsubmit-service
    ports:
      - 10013:10013
  

  invitepc-service:
    hostname: sc
    image: sc/sc-invitepc-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: invitepc-service
    ports:
      - 10014:10014


  getinvitation-service:
    hostname: sc
    image: sc/sc-getinvitation-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/    
    container_name: getinvitation-service
    ports:
      - 10015:10015

  papersubmit-service:
    hostname: sc
    image: sc/papersubmit-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: papersubmit-service
    ports:
      - 10016:10016

  beginexaminescripts-service:
    hostname: sc
    image: sc/beginexaminescripts-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: beginexaminescripts-service
    ports:
      - 10017:10017

  exmainemanuscripts-service:
    hostname: sc
    image: sc/sc-exmainemanuscripts-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: exmainemanuscripts-service
    ports:
      - 10018:10018


  endexmainenemanuscripts-service:
    hostname: sc
    image: sc/sc-endexmainenemanuscripts-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: endexmainenemanuscripts-service
    ports:
      - 10019:10019

  discussion-service:
    hostname: sc
    image: sc/discussion-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: discussion-service
    ports:
      - 10020:10020


  releasefirstresult-service:
    hostname: sc
    image: sc/sc-releasefirstresult-service:0.0.1
    environment:      
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: releasefirstresult-service
    ports:
      - 10021:10021

  rebuttal-service:
    hostname: sc
    image: sc/sc-rebuttal-service
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: rebuttal-service
    ports: 
      - 10022:10022


  releasefinalresult-service:
    hostname: sc
    image: sc/sc-releasefinalresult-service:0.0.1
    environment:      
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: releasefinalresult-service
    ports:
      - 10023:10023

  getinvitationIsent-service:
    hostname: sc
    image: sc/sc-getinvitationIsent-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: getinvitationIsent-service
    ports:
      - 10024:10024

  modifyarticleinfo-service:
    hostname: sc
    image: sc/sc-modifyarticleinfo-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: modifyarticleinfo-service
    ports:
      - 10025:10025


  confirmfinish-service:
    hostname: sc
    image: sc/sc-confirmfinish-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: confirmfinish-service
    ports:
      - 10026:10026

  getmymeetingapplication-service:
    hostname: sc
    image: sc/sc-getmymeetingapplication-service:0.0.1
    environment:       
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: getmymeetingapplication-service
    ports:
      - 10027:10027

  registerlogin-service:
    hostname: sc
    image: sc/sc-registerlogin-service:0.0.1
    environment:      
    - eureka.client.serviceUrl.defaultZone=http://root:root@eureka-service:10010/eureka/     
    container_name: registerlogin-service
    ports:
      - 10028:10028

  
  
  