apiVersion: v1
kind: Service
metadata:
  name: starchair-frontend
  namespace: ase-ns-10
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starchair-frontend-deploy
  namespace: ase-ns-10
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image:  registry.cn-hangzhou.aliyuncs.com/youngf/starchair-frontend:1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"

